library(pacman)
p_load(dplyr, tidyr, here)

SOURCE <- "withMUTATIONS/"

setwd("../")
files_path <- paste0(getwd(), '/refract-data/', SOURCE)
data_out <- paste0(files_path, 'processed/')
#marbox <- 'acnA'
#det_ini <- paste0(marbox, '_ini_details.csv')
#det_96h <- paste0(marbox, '_96h_details.csv')

det_ini <- 'all_ini_details.csv'
det_96h <- 'all_96h_details.csv'

simp_ord <- c('N','P','O')
det_ord <- c('N','P','B','A','O')

marbox_order = c("marRAB", "yba0", "rob", "acnA", "acrAB", "fldB", "fldA", "fpr", "hdeA", "mdtG", "poxB", "purA", "ribA", "slp")

initial_filter <- function(files_path, det_file, print_summaries) {
  
  df <- read.csv(paste0(files_path, det_file), stringsAsFactors=FALSE)
  
  df <- df%>%
    mutate(across(any_of(colnames(df)[grepl("res[0-9]_tpsimp", colnames(df))]), ~ factor(.x, levels=c(simp_ord))),
           across(any_of(colnames(df)[grepl("res[0-9]_tpdet", colnames(df))]), ~ factor(.x, levels=c(det_ord))),
           marbox=factor(marbox, levels=!!marbox_order))
  
  # Number of reads
  df_summ <- df%>%group_by(marbox)%>%summarise(cnt=sum(cnt))
  df_summ1 <- df%>%
    select(marbox, peptide)%>%distinct()%>% # Had to add this step in case we use the file with mismatches in marboxes
    group_by(marbox)%>%tally()
  if (print_summaries) {
    print("Original total counts")
    print(df_summ)
    print("\n")
    print("Original unique peptides")
    print(df_summ1)
  }
  
  # Number of reads with invalid AAs or NTs
  if ("invalid_nt" %in% colnames(df)){
    df_inv <- df%>%filter(cnt_tpsimp_other>0|invalid_nt=="True")
  } else {
    df_inv <- df%>%filter(cnt_tpsimp_other>0)
  }
  df_inv <- df_inv%>%group_by(marbox)%>%summarise(cnt=sum(cnt))
  if (print_summaries) {
    print("Invalid counts")
    print(df_inv)
  }
  
  # Steps required to remove duplication generated by marboxes, when allowing mutations
  if ("invalid_nt" %in% colnames(df)){
    df <- df%>%filter(cnt_tpsimp_other==0&invalid_nt=="False")%>%
      select(-invalid_nt, -nts)%>%
      group_by(across(c(-cnt)))%>%
      summarise(cnt=sum(cnt))%>%
      arrange(marbox, desc(cnt))
  } else {
    df <- df%>%filter(cnt_tpsimp_other==0)
  }
  df <- df%>%
    ungroup()%>%
    group_by(marbox)%>%
    mutate(order_marbox = dplyr::row_number())
  
  # Different peptides
  df_summ2 <- df%>%group_by(marbox)%>%tally()
  if (print_summaries) {
    print("Final peptides (without invalid)")
    print(df_summ2)
  }
  
  df_summ <- df%>%group_by(marbox)%>%summarise(cnt=sum(cnt))
  if (print_summaries) {
    print("Final counts (without invalid)")
    print(df_summ)
  }
  return(df)
}

# Initial dataframes
df_ini <- initial_filter(files_path, det_ini, FALSE)
df_96h <- initial_filter(files_path, det_96h, FALSE)

df_ini_sel <- df_ini%>%select(marbox, peptide, cnt)
df_96h_sel <- df_96h%>%select(marbox, peptide, cnt, order_marbox)

df_intersect <- df_ini_sel%>%
  inner_join(df_96h_sel, by=c("marbox", "peptide"), suffix=c("_ini", "_96h"))%>%
  group_by(marbox)%>%tally()